//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrafikPracy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Czas> Czas { get; set; }
        public virtual DbSet<Dzien> Dzien { get; set; }
        public virtual DbSet<DzienRoboczyPracownika> DzienRoboczyPracownika { get; set; }
        public virtual DbSet<DzienTygodnia> DzienTygodnia { get; set; }
        public virtual DbSet<DzienUrlopu> DzienUrlopu { get; set; }
        public virtual DbSet<Godzina> Godzina { get; set; }
        public virtual DbSet<Grafik> Grafik { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<PracownikNaStanowisku> PracownikNaStanowisku { get; set; }
        public virtual DbSet<Stanowisko> Stanowisko { get; set; }
        public virtual DbSet<StanowiskoMiejsca> StanowiskoMiejsca { get; set; }
        public virtual DbSet<StanowiskoPracownika> StanowiskoPracownika { get; set; }
        public virtual DbSet<Urlop> Urlop { get; set; }
    }
}
