//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrafikPracy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DzienUrlopu
    {
        public int Id { get; set; }
        public int Urlop_Id { get; set; }
        public System.DateTime Dzien_Data { get; set; }
    
        public virtual Dzien Dzien { get; set; }
        public virtual Urlop Urlop { get; set; }
    }
}
