//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrafikPracy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urlop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urlop()
        {
            this.DzienUrlopu = new HashSet<DzienUrlopu>();
        }
    
        public int Id { get; set; }
        public bool Zatwierdzony { get; set; }
        public string Powod { get; set; }
        public int Pracownik_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DzienUrlopu> DzienUrlopu { get; set; }
        public virtual Pracownik Pracownik { get; set; }
    }
}
